name: Bump version
on:
  pull_request:
    types:
      - closed
    branches:
      - master
  push:
    branches:
      - master

jobs:
  auto-tag-pr:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.merge_commit_sha }}
        fetch-depth: '0'
    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@1.64.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
  auto-tag:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
    - uses: 8BitJonny/gh-get-current-pr@2.2.0
      id: check_pr
    - uses: actions/checkout@v3
      with:
        fetch-depth: '0'
    - uses: hmarr/debug-action@v2
    - if: steps.check_pr.outputs.pr_found == 'false'
      name: Bump version and push tag
      uses: anothrNick/github-tag-action@1.64.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
